import type { Metadata } from 'next';
import { Manrope, Marcellus } from 'next/font/google';
import './globals.css';
import Nav from '@/layouts/Nav';
import Footer from '@/layouts/Footer';
import { FooterBanner } from '@/layouts/Footer';

const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin'],
});
const marcellus = Marcellus({
    variable: '--font-marcellus',
    subsets: ['latin'],
    weight: '400',
});

export const metadata: Metadata = {
    title: 'MevSpecialistHospital',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${manrope.variable} ${marcellus.variable} antialiased`}
            >
                <div>
                    <Nav />
                    {children}
                    <FooterBanner />
                    <Footer />
                </div>
            </body>
        </html>
    );
}
